version: "3"

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=testUserIntrospection
      - POSTGRES_PASSWORD=HurricaneStartingSample1934
      - POSTGRES_DB=introspection
    volumes:
      - postgres:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres: null
