version: "3"

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpasswd
      - POSTGRES_DB=stepzen_demo
    volumes:
      - postgres:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres: null
